version: '3.7'

services:

  react-covid:
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/opt/node_app
      - node_modules:/opt/node_app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: